name: GhostPRO_Final_Build
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Free Space
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc

      - name: Install System Deps
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev build-essential
          pip install --user --upgrade "Cython<3.0" buildozer

      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Мы НЕ используем 'yes |', чтобы избежать Broken Pipe.
          # Флаг --auto и настройка в spec файле сделают всё сами.
          buildozer android debug
        env:
          BUILDOZER_ALLOW_ORG_GHOST: 1
          # Принимаем лицензии через переменную окружения (доп. страховка)
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GhostPRO-Ready
          path: bin/*.apk
