name: Ghost_Build_Mobile
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip cmake libffi-dev libssl-dev build-essential
          pip install --user --upgrade "Cython<3.0" buildozer
      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Собираем без лишних вопросов
          buildozer android debug
        env:
          BUILDOZER_ALLOW_ORG_GHOST: 1
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Ghost-APK-Mobile
          path: bin/*.apk
