name: GhostPRO_Universal_Build
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install System Deps
        run: |
          sudo apt update
          # Убраны старые пакеты, вызывавшие ошибки на твоих скринах
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev build-essential
          pip install --user --upgrade "Cython<3.0" buildozer

      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Автоматическое принятие лицензий перед сборкой
          yes | sdkmanager --licenses || true
          buildozer android debug
        env:
          BUILDOZER_ALLOW_ORG_GHOST: 1

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: GhostPRO_MultiArch_v1_6
          path: bin/*.apk
