[app]
title = Ghost PRO
package.name = ghostmessenger
package.domain = org.ghost.pro
source.dir = .
source.include_exts = py,png,jpg,kv,html,js,json
version = 2.1

# Включаем всё, чтобы APK стал "тяжелым" и стабильным
requirements = python3,kivy==2.2.1,pyjnius,android,requests,pyrebase4,urllib3,certifi,openssl,hostpython3,sqlite3

orientation = portrait
android.api = 34
android.minapi = 24
android.ndk = 25b
# Fat APK: поддержка всех ядер
android.archs = arm64-v8a, armeabi-v7a

android.permissions = INTERNET, ACCESS_NETWORK_STATE, WRITE_EXTERNAL_STORAGE
android.manifest.uses_cleartext_traffic = True
android.accept_sdk_license = True

# Черный экран загрузки
android.presplash_color = #000000
presplash.filename = 
icon.filename = icon.png

[buildozer]
log_level = 2
warn_on_root = 1
