name: Build Ghost PRO APK
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          # Важно: фиксируем Cython, который любит Kivy 2.2.1
          pip3 install --user --upgrade "Cython<3.0" buildozer 

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Соглашаемся с лицензиями и запускаем
          yes | buildozer android debug
        env:
          BUILDOZER_ALLOW_ORG_GHOST: 1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GhostPRO-Final
          path: bin/*.apk
