name: Build Ghost PRO 2026
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # Используем готовый образ, где всё уже настроено
    container:
      image: ghcr.io/kivy/buildozer:master

    steps:
      - uses: actions/checkout@v4

      - name: Build APK with Buildozer
        run: |
          # Соглашаемся с лицензиями внутри контейнера
          yes | buildozer android debug
        env:
          BUILDOZER_ALLOW_ORG_GHOST: 1

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: GhostPRO-2026-Ready
          path: bin/*.apk
