name: Ghost_Build
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Deps
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev build-essential
          pip install --user --upgrade "Cython<3.0" buildozer
      - name: Build
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Запуск без ора в консоль (без yes)
          buildozer android debug
        env:
          BUILDOZER_ALLOW_ORG_GHOST: 1
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Ghost-APK
          path: bin/*.apk
