name: GhostPRO_Build
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev build-essential
          # Устанавливаем Rust для библиотеки cryptography
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          pip install --user --upgrade "Cython<3.0" buildozer

      - name: Build APK
        run: |
          source $HOME/.cargo/env
          export PATH=$PATH:$HOME/.local/bin
          # Запускаем без 'yes |'. Buildozer возьмет настройки из .spec
          buildozer android debug
        env:
          BUILDOZER_ALLOW_ORG_GHOST: 1
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GhostPRO-Ready
          path: bin/*.apk
